name: Edit Release Notes

on:
  release:
    types: [published]

jobs:
  release:
    uses: happy-changelog/happy-changelog-workflow/.github/workflows/edit-release.yml@v1.0.0
    permissions:
      contents: write
    with:
      changelog-file: CHANGELOG.md
